version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: real-estate-gui-app:latest
    container_name: real-estate-gui-app
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
